openapi: 3.0.0
info:
  title: Auctionable Change
  description: Backend API for the Auctionable Change mobile application.
                Created by Turing School of Software and Design students
                Stephanie Friend, Kevin McGrevey, Andrew Reid.
  version: 1.0.0
  authors: Stephanie Friend, Kevin McGrevey, Andrew Reid
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://auctionable-change-api.herokuapp.com
    description: Main (production) server
  - url: http://127.0.0.1:5000
    description: Local (development) server
tags:
  - name: Items
    description: Endpoints for Item CRUD
  - name: Bids
    description: Endpoints for Bid CRUD
  - name: Charities
    description: Endpoints for querying Charity Navigator
paths:
  /items:
    get:
      summary: Returns a list of all items.
      tags:
        - Items
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Items'
              examples:
                Item:
                  $ref: '#/components/examples/Items'

        '400':
          description: Bad Request
    post:
      summary: Creates a new item.
      tags:
        - Items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemRequest'
            examples:
              ItemRequest:
                $ref: '#/components/examples/ItemRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
              examples:
                Item:
                  $ref: '#/components/examples/Item'
        '400':
          description: Bad Request
  /items/{item_id}:
    get:
      summary: Returns a selected item.
      parameters:
        - in: path
          name: item_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the item to get
      tags:
        - Items
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
              examples:
                Item:
                  $ref: '#/components/examples/Item'

        '404':
          description: Item not found
    put:
      summary: Updates a selected item.
      parameters:
        - in: path
          name: item_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the item to update
      tags:
        - Items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
            examples:
              Item:
                $ref: '#/components/examples/Item'
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
            examples:
              Item:
                $ref: '#/components/examples/Item'
        '404':
          description: Item not found
    delete:
      summary: Removes an item.
      parameters:
        - in: path
          name: item_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the item to delete
      tags:
        - Items
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
              examples:
                Item:
                  $ref: '#/components/examples/Item'
        '403':
          description: Cannot delete item with associated bids
        '404':
          description: Item not found
  /items/available:
    get:
      summary: Returns a list of available items.
      tags:
        - Items
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Items'
              examples:
                Item:
                  $ref: '#/components/examples/Items'

        '400':
          description: Bad Request
  /items/pending:
    get:
      summary: Returns a list of items for which an auction has concluded, but the item has not yet been sold.
      tags:
        - Items
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Items'
              examples:
                Item:
                  $ref: '#/components/examples/Items'

        '400':
          description: Bad Request
  /items/sold:
    get:
      summary: Returns a list of items which have been sold.
      tags:
        - Items
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Items'
              examples:
                Item:
                  $ref: '#/components/examples/Items'

        '400':
          description: Bad Request
  /bids:
      get:
        summary: Returns a list of available bids.
        tags:
          - Bids
        responses:
          '200':    # status code
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Bids'
                examples:
                  Bid:
                    $ref: '#/components/examples/Bids'
          '400':
            description: Bad Request
      post:
        summary: Creates a new bid.
        tags:
          - Bids
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BidRequest'
              examples:
                BidRequest:
                  $ref: '#/components/examples/BidRequest'
        responses:
          '200':
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Bid'
                examples:
                  Bid:
                    $ref: '#/components/examples/Bid'
          '400':
            description: Bad Request
  /bids/{bid_id}:
    get:
      summary: Returns a selected bids.
      parameters:
        - in: path
          name: bid_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the bid to get
      tags:
        - Bids
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bid'
              examples:
                Bid:
                  $ref: '#/components/examples/Bid'
        '404':
          description: Bid not found
    put:
      summary: Updates a selected bids.
      parameters:
        - in: path
          name: bid_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the bid to update
      tags:
        - Bids
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BidRequest'
            examples:
              BidRequest:
                $ref: '#/components/examples/BidRequest'
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bid'
              examples:
                Bid:
                  $ref: '#/components/examples/Bid'
        '404':
          description: Bid not found
    delete:
      summary: Removes an bid.
      parameters:
        - in: path
          name: bid_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the bid to delete
      tags:
        - Bids
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bid'
              examples:
                Bid:
                  $ref: '#/components/examples/Bid'
        '404':
          description: Bid not found
  /bids/winners:
    get:
      summary: Returns a list of all winning bids.
      tags:
        - Bids
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bids'
              examples:
                Item:
                  $ref: '#/components/examples/Bids'

        '400':
          description: Bad Request
  /charities:
    get:
      summary: Returns a list of rated charities from Charity Navigator.
      tags:
        - Charities
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Charity'
              examples:
                Bid:
                  $ref: '#/components/examples/Charities'
        '400':
          description: Bad Request
  /charities/{search_term}:
    get:
      summary: Searches for charities which match search term.
      parameters:
        - in: path
          name: search_term
          schema:
            type: string
          required: true
          description: String for which you wish to search
      tags:
        - Charities
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Charities'
              examples:
                Bid:
                  $ref: '#/components/examples/Charities'
        '400':
          description: Bad Request
components:
  schemas:
    Items:
      properties:
        count:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
    Item:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        donor:
          type: string
        donor_email:
          type: string
        status:
          type: string
        category:
          type: string
        charity:
          type: string
        charity_url:
          type: string
        charity_score:
          type: string
        charity_score_image:
          type: string
        image:
          type: string
        bids:
          type: array
          items:
            $ref: '#/components/schemas/Bid'
    ItemRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        donor:
          type: string
        donor_email:
          type: string
        status:
          type: string
        category:
          type: string
        charity:
          type: string
        charity_url:
          type: string
        charity_score:
          type: string
        charity_score_image:
          type: string
        image:
          type: string
    Bids:
      properties:
        count:
          type: integer
        bids:
          type: array
          items:
            $ref: '#/components/schemas/Bid'
    Bid:
      type: object
      properties:
        id:
          type: integer
        item_id:
          type: integer
        bidder_name:
          type: string
        bidder_email:
          type: string
        amount:
          type: number
          format: float
        street_address:
          type: string
        city:
          type: string
        state:
          type: string
        zip_code:
          type: string
        receipt:
          type: string
    BidRequest:
      type: object
      properties:
        item_id:
          type: integer
        bidder_name:
          type: string
        bidder_email:
          type: string
        amount:
          type: number
          format: float
        street_address:
          type: string
        city:
          type: string
        state:
          type: string
        zip_code:
          type: string
        receipt:
          type: string
    Charity:
      type: object
      properties:
        id:
          type: integer
        url:
          type: string
        name:
          type: string
        rating:
          type: integer
        rating_image:
          type: string
    Charities:
      properties:
        count:
          type: integer
        charities:
          type: array
          items:
            $ref: '#/components/schemas/Charity'
  examples:
    Items:
      value:
        count: 2
        items:
        - id: 1
          title: Photo
          description: Image of Johnny Cash
          price: 49.99
          donor: Andrew Reid
          donor_email: areid@example.com
          category: home
          charity: ProPublcia
          charity_url: https://www.charitynavigator.org/?bay=search.summary&orgid=13005&utm_source=DataAPI&utm_content=6bc9f3c8
          charity_score: 4
          charity_score_image: https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/stars/4stars.png
          image: https://3w8dlo2orf8y3crtc22sslbh-wpengine.netdna-ssl.com/wp-content/uploads/2020/02/johnny-cash-1-.jpg
          bids: []
        - id: 2
          title: Album
          description: The Clash London Calling
          price: 10.00
          donor: Joe Strummer
          donor_email: joestrummer@example.com
          category: home
          charity: Center for People in Need
          charity_url: https://www.charitynavigator.org/?bay=search.summary&orgid=12688&utm_source=DataAPI&utm_content=6bc9f3c8
          charity_score: 3
          charity_score_image: https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/stars/3stars.png
          image: https://img.discogs.com/HWBBtcFnGxd7ZOoN3wskQ8kh7ro=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/R-470912-1248752385.jpeg.jpg
          bids:
          - id: 2
            bidder_name: Johnny McBuyingstuff
            bidder_email: jmb@example.com
            amount: 99.99
            street_address: 123 Main St.
            city: Coshocton
            state: OH
            zip_code: 43812
            receipt: https://lh3.googleusercontent.com/proxy/ZawdSVwkLnl4q56J9ffJxuPhWvdJ4J0P8nJWNKdA8SKWo0_TYZjR4R8yu-yCAwl-CVHUdYKj8s65LofwLcVWpvqXrVO2xNku1050T9F7QFY
            item_id: 1
    Item:
      value:
        id: 1
        title: Photo
        description: Image of Johnny Cash
        price: 49.99
        donor: Andrew Reid
        donor_email: areid@example.com
        category: home
        charity: ProPublcia
        charity_url: https://www.charitynavigator.org/?bay=search.summary&orgid=13005&utm_source=DataAPI&utm_content=6bc9f3c8
        charity_score: 4
        charity_score_image: https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/stars/4stars.png
        image: https://3w8dlo2orf8y3crtc22sslbh-wpengine.netdna-ssl.com/wp-content/uploads/2020/02/johnny-cash-1-.jpg
        bids: []
      summary: Sample item object
    ItemRequest:
      value:
        title: Photo
        description: Image of Johnny Cash
        price: 49.99
        donor: Andrew Reid
        donor_email: areid@example.com
        category: home
        charity: ProPublcia
        charity_url: https://www.charitynavigator.org/?bay=search.summary&orgid=13005&utm_source=DataAPI&utm_content=6bc9f3c8
        charity_score: 4
        charity_score_image: https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/stars/4stars.png
        image: https://3w8dlo2orf8y3crtc22sslbh-wpengine.netdna-ssl.com/wp-content/uploads/2020/02/johnny-cash-1-.jpg
      summary: Sample item object
    Bids:
      value:
        count: 2
        bids:
        - id: 1
          bidder_name: Johnny McBuyingstuff
          bidder_email: jmb@example.com
          amount: 99.99
          street_address: 123 Main St.
          city: Coshocton
          state: OH
          zip_code: 43812
          receipt: https://lh3.googleusercontent.com/proxy/ZawdSVwkLnl4q56J9ffJxuPhWvdJ4J0P8nJWNKdA8SKWo0_TYZjR4R8yu-yCAwl-CVHUdYKj8s65LofwLcVWpvqXrVO2xNku1050T9F7QFY
          item_id: 1
        - id: 2
          bidder_name: Sally Simpson
          bidder_email: sally@example.com
          amount: 55.55
          street_address: 456 Main St.
          city: Coshocton
          state: OH
          zip_code: 43812
          receipt: https://lh3.googleusercontent.com/proxy/ZawdSVwkLnl4q56J9ffJxuPhWvdJ4J0P8nJWNKdA8SKWo0_TYZjR4R8yu-yCAwl-CVHUdYKj8s65LofwLcVWpvqXrVO2xNku1050T9F7QFY
          item_id: 2
    Bid:
      value:
        id: 1
        bidder_name: Johnny McBuyingstuff
        bidder_email: jmb@example.com
        amount: 99.99
        street_address: 123 Main St.
        city: Coshocton
        state: OH
        zip_code: 43812
        receipt: https://lh3.googleusercontent.com/proxy/ZawdSVwkLnl4q56J9ffJxuPhWvdJ4J0P8nJWNKdA8SKWo0_TYZjR4R8yu-yCAwl-CVHUdYKj8s65LofwLcVWpvqXrVO2xNku1050T9F7QFY
        item_id: 1
      summary: Sample bid object
    BidRequest:
      value:
        bidder_name: Johnny McBuyingstuff
        bidder_email: jmb@example.com
        amount: 99.99
        street_address: 123 Main St.
        city: Coshocton
        state: OH
        zip_code: 43812
        receipt: https://lh3.googleusercontent.com/proxy/ZawdSVwkLnl4q56J9ffJxuPhWvdJ4J0P8nJWNKdA8SKWo0_TYZjR4R8yu-yCAwl-CVHUdYKj8s65LofwLcVWpvqXrVO2xNku1050T9F7QFY
        item_id: 1
      summary: Sample bid object
    Charities:
      value:
        count: 2
        charities:
        - id: 593330495
          url: https://www.charitynavigator.org/?bay=search.summary&orgid=8804&utm_source=DataAPI&utm_content=6bc9f3c8
          name: "Big Cat Rescue"
          rating: 4
          rating_image: https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/stars/4stars.png
        - id: 911726410
          url: https://www.charitynavigator.org/?bay=search.summary&orgid=18675&utm_source=DataAPI&utm_content=6bc9f3c8
          name: "Whatcom Community Foundation"
          rating: 4
          rating_image: https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/stars/4stars.png
